
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'

set -g mouse on

set -g status-bg black

set -g status-fg white<script>

set -g status-left "#[fg-cyan]%H:%M %d.%m"

set -g status-right "#(tmux-cpu) | #(tmux-battery)   "

run '~/.tmux/plugins/tpm/tpm'

unbind C-b 
unbind-key f
unbind-key j
unbind-key v
unbind-key Tab
unbind-key h
unbind-key c

set-option -g prefix Tab
bind Tab send-prefix 
bind-key c new-window  
bind-key j next-window
bind-key f previous-window
bind-key h split-window -h
bind-key v split-window -v
